config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  root to: "pages#home"
  get "about", to: "pages#about"
  get "features", to: "pages#features"
  get "dashboard", to: "pages#dashboard"
  get 'content', to: "pages#content"
  get "calculator", to: "pages#calculator"
  get "distance", to: 'pages#distance'
  get "converted", to: 'pages#converted'
  get "chatrooms", to: 'pages#chatrooms'
  resources :articles do
    resources :likes
  end
  resources :topics do
    resources :replies, only: [:new, :create] do
      resources :comments, only: [:create]
    end
  end
  resources :replies, only: [:destroy]
  resources :comments, only: [:destroy]
  resources :chatrooms, only: :show do
    resources :messages, only: :create
  end
  resources :requests, only: [:create, :update, :destroy]

  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html
  # Defines the root path route ("/")
  # root "articles#index"
end

app/models/article.rb
class Article < ApplicationRecord
  belongs_to :user
  belongs_to :category
  has_many :likes, dependent: :destroy
  validates :title, :subtitle, :rich_body, presence: true
  has_one_attached :photo
  has_rich_text :rich_body
end

app/controllers/articles_controller.rb
class ArticlesController < ApplicationController
  before_action :set_article, only: %i[show destroy edit update destroy]
  skip_before_action :authenticate_user!, only: %i[home index show]

  def index
    skip_policy_scope
    if params[:query].present?
      @articles = Article.where("title ILIKE ? AND accepted = ?", "%#{params[:query]}%", true)
    else
      @articles = Article.where(accepted: true).order("created_at DESC")
    end
    respond_to do |format|
      if turbo_frame_request?
        format.html { render partial: 'shared/list', locals: { articles: @articles } }
      else
        format.html
      end
    end
    @believer = params[:believer] == "true" if params[:believer]
  end

  def show
    authorize @article
  end

  def new
    @article = Article.new
    @categories = Category.all
    authorize @article
  end

  def create
    @category = Category.find(params[:article][:category])
    @article = Article.new(article_params)
    @article.category = @category
    @article.user = current_user
    authorize @article
    if @article.save
      redirect_to article_path(@article), notice: "Article successfully created!"
    else
      render :new, status: :unprocessable_entity
    end
  end

  def edit
    @categories = Category.all
    authorize @article
  end

  def update
    if params[:accept] == 'true'
      @article.accepted = true
      authorize @article
      @article.save
      @articles = Article.where(accepted: false)
      render partial: 'pages/newarticles'
    else
      @category = Category.find(params[:article][:category])
      @article.category = @category
      @article.accepted = false
      authorize @article
      if @article.update(article_params)
        redirect_to @article, notice: "Article was successfully updated."
      else
        render :edit, status: :unprocessable_entity
      end
    end
  end

  def destroy
    authorize @article
    @article.destroy
    @articles = Article.where(accepted: false)
    render partial: 'pages/newarticles'
  end

  private

  def set_article
    @article = Article.find(params[:id])
  end

  def article_params
    params.require(:article).permit(:title, :subtitle, :rich_body, :photo)
  end
end

app/views/articles/edit.html.erb
<%= render 'shared/navbar' %>
<section class="position-relative py-4 py-xl-5">
  <div class="container position-relative">
    <div class="row d-flex justify-content-center">
      <div class="col-sm-5 col-md-6 col-xxl-8">
        <div class="card mb-5">
          <div class="card-body p-sm-5">
            <h3 class="mb-4">Update your article</h3>
            <%= simple_form_for(@article) do |f| %>
              <%= f.error_notification %>
              <%= f.error_notification message: f.object.errors[:base].to_sentence if f.object.errors[:base].present? %>
              <div class="form-inputs mb-3">
                <%= f.input :photo, label:'Photo', as: :file %>
                <%= f.input :category, label:'Category', collection: @categories %>
                <%= f.input :title, label:'Title'%>
                <%= f.input :subtitle, label:'Subtitle'%>
                <div class="form-inputs">
                  <%= f.rich_text_area :rich_body %>
                </div>
              </div>
              <div class="form-actions mb-2 pt-4">
                <%= f.button :submit, 'Submit Updates', class: 'btn btn-dark rounded-pill d-block w-100' %>
              </div>
            <% end %>
          </div>
        </div>
      </div>
    </div>
  </div>
</section>

app/views/articles/index.html.erb
<%= render 'shared/navbar' %>
<%= render 'shared/list', articles: @articles %>
<%= render 'shared/converter' %>

app/views/articles/new.html.erb
<%= render 'shared/navbar' %>
<section class="position-relative py-4 py-xl-5">
  <div class="container position-relative">
    <div class="row d-flex justify-content-center">
      <div class="col-sm-5 col-md-6 col-xxl-8">
        <div class="card mb-5">
          <div class="card-body p-sm-5">
            <h3 class="mb-4">Create your article</h3>
            <%= simple_form_for(@article) do |f| %>
              <%= f.error_notification %>
              <%= f.error_notification message: f.object.errors[:base].to_sentence if f.object.errors[:base].present? %>
              <div class="form-inputs mb-3">
                <%= f.input :photo, label:'Photo', as: :file %>
                <%= f.input :category, label:'Category', collection: @categories %>
                <%= f.input :title, label:'Title'%>
                <%= f.input :subtitle, label:'Subtitle'%>
                <div class="form-inputs">
                  <%= f.rich_text_area :rich_body %>
                </div>
              </div>
              <div class="form-actions mb-2 pt-4">
                <%= f.button :submit, 'New article', class: 'btn btn-dark rounded-pill d-block w-100' %>
              </div>
            <% end %>
          </div>
        </div>
      </div>
    </div>
  </div>
</section>

app/views/articles/show.html.erb
<%= render 'shared/navbar' %>
<%= render 'shared/converter' %>
<div class="container">
  <h2 class="article-title"><%= @article.title %></h2>
  <p class="article-user">
  Published <%=time_ago_in_words(@article.created_at)%> ago, sent by:
  <strong><%= @article.user.nickname%></strong></p>
  <br/>
  <div class="article-grid">
    <div class="social-icons text-center">
      <i class="fa-brands fa-facebook"></i>
      <i class="fa-brands fa-instagram"></i>
      <i class="fa-brands fa-twitter"></i>
    </div>
    <div class="article-image">
      <%= cl_image_tag @article.photo.key, height: 1920, width: 1080, crop: :limit if @article.photo.attached? %>
      <div>
        <div class="article-text">
          <p><%= @article.rich_body %></p>
        </div>
      </div>
    </div>
    <div class="social-icons text-center">
      <% pre_like = @article.likes.find { |like| like.user_id == current_user.id} if current_user%>
      <% if pre_like %>
        <%= button_to(article_like_path(@article, pre_like), method: :delete, class: "") do %>
        <span class= "fa-solid fa-heart fa-lg icon-heart"><span>
        <% end %>
      <% else %>
          <%= button_to(article_likes_path(@article), method: :post, class: "") do %>
          <span class= "fa-solid fa-heart fa-lg icon-heart-off"><span>
          <% end %>
      <% end %>
      <p class="btn btn-dark btn-sm"><%= @article.likes.count %></p>
      </div>
    </div>
  </div>
</div>