config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  root to: "pages#home"
  get "about", to: "pages#about"
  get "features", to: "pages#features"
  get "dashboard", to: "pages#dashboard"
  get 'content', to: "pages#content"
  get "calculator", to: "pages#calculator"
  get "distance", to: 'pages#distance'
  get "converted", to: 'pages#converted'
  get "chatrooms", to: 'pages#chatrooms'
  resources :articles do
    resources :likes
  end
  resources :topics do
    resources :replies, only: [:new, :create] do
      resources :comments, only: [:create]
    end
  end
  resources :replies, only: [:destroy]
  resources :comments, only: [:destroy]
  resources :chatrooms, only: :show do
    resources :messages, only: :create
  end
  resources :requests, only: [:create, :update, :destroy]

  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html
  # Defines the root path route ("/")
  # root "articles#index"
end

app/models/topic.rb
class Topic < ApplicationRecord
  belongs_to :user
  has_many :replies, dependent: :destroy
  validates :title, :description, presence: true
  validates :title, uniqueness: { case_sensitive: false }
end

app/controllers/topics_controller.rb
class TopicsController < ApplicationController
  before_action :set_topic, only: %i[show destroy edit update]
  skip_before_action :authenticate_user!, only: %i[home index show]
  def index
    skip_policy_scope
    @topics = Topic.all.order("created_at DESC")
    @topic = Topic.new
  end

  def show
    skip_authorization
    @topic = Topic.find(params[:id])
    @reply = Reply.new
    @comment = Comment.new
  end

  def new
    @topic = Topic.new
    @topic.user = current_user
    authorize @topic
  end

  def create
    @topic = Topic.new(topic_params)
    @topic.user = current_user
    authorize @topic
    if @topic.save
      redirect_to topic_path(@topic), notice: "Topic created!"
    else
      render :new, status: :unprocessable_entity
    end
  end

  def edit
    @topic = Topic.find(params[:id])
    authorize @topic
  end

  def destroy
    @topic = Topic.find(params[:id])
    authorize @topic
    @topic.destroy
    redirect_to topics_url, notice: "Topic successfully destroyed."
  end

  def update
    @topic = Topic.find(params[:id])
    authorize @topic
    if @topic.update(topic_params)
      redirect_to @topic, notice: "Topic successfully updated."
    else
      render :edit, status: :unprocessable_entity
    end
  end

  private

  def set_topic
    @topic = Topic.find(params[:id])
  end

  def topic_params
    params.require(:topic).permit(:title, :description)
  end
end

app/views/topics/_form.html.erb
<%= simple_form_for(@topic) do |f|%>
  <div class="form-comment p-4 text-center">
    <%= f.error_notification %>
    <%= f.error_notification message: f.object.errors[:base].to_sentence if f.object.errors[:base].present? %>
    <%=f.input :title%>
    <%=f.input :description%>
    <% if current_user %>
      <%= f.button :submit, 'Submit', class: 'btn btn-dark rounded-pill d-block w-100' %>
    <%end%>
  <%end%>
</div>

app/views/topics/_form_comment.html.erb
<%= simple_form_for [ @topic, reply, @comment] do |f| %>
<div class="container">
<div class="rounded-style form-comment-1 p-4 text-center">
    <%= f.error_notification %>
    <%= f.error_notification message: f.object.errors[:base].to_sentence if f.object.errors[:base].present? %>

    <div class="form-inputs">
      <%= f.input :content, label:"Answer" %>
    </div>

    <div class="form-actions">
      <%= f.button :submit, 'Submit', class: 'btn btn-dark rounded-pill d-block w-100' %>
    </div>

  <% end %>
</div>
</div>

app/views/topics/_form_reply.html.erb
<%= simple_form_for [@topic, @reply] do |f| %>
<div class="container">
<div class="rounded-style form-comment p-4 text-center">
    <%= f.error_notification %>
    <%= f.error_notification message: f.object.errors[:base].to_sentence if f.object.errors[:base].present? %>

    <div class="form-inputs">
      <%= f.input :content, label:"Comment" %>
    </div>

    <% if current_user %>
    <div class="form-actions">
      <%= f.button :submit, 'Add Comment', class: 'btn btn-dark rounded-pill d-block w-100' %>
    </div>
  <% end %>
   <% end %>
</div>
</div>

app/views/topics/edit.html.erb
<%= render 'shared/navbar' %>
<h1>Editing topic</h1>
<div class="form-comment p-4 text-center">
  <%= render "form", topic: @topic %>
  <br>
  <div>
    <%= link_to "Show this topic", @topic %> |
    <%= link_to "Back to topics", topics_path %>
  </div>
</div>

app/views/topics/index.html.erb
<%= render 'shared/navbar' %>
<%= render 'shared/converter' %>

<div class="cards">
<div class="forum bg-dark">
  <div class=" header d-flex align-items-center justify-content-between">
    <h2 class=" text-dark">RoundEarthForum</h2>
    <% if current_user %>
      <a class=" bt text-light btn btn-light bg-dark" data-bs-toggle="collapse" href="#collapseExample" role="button" aria-expanded="false" aria-controls="collapseExample">New Post</a>
    <%end%>
  </div>
<div class="back-topics py-3" style="background-image: linear-gradient(rgba(0,0,0,0.4),rgba(0,0,0,0.4)), url(https://images.pexels.com/photos/586056/pexels-photo-586056.jpeg);">
  <div class="container">
    <div class="collapse mx-5" id="collapseExample">
      <%= render"form" %>
    </div>
    <% @topics.each do |topic| %>
      <div class="topic-topic-1 m-5 px-5 py-3 text-center rounded-style">


              Published <%=time_ago_in_words(topic.created_at)%> ago,
              sent by: <strong><%= topic.user.nickname%></strong>
        </p>
        <%= link_to topic_path(topic), class:'text-decoration-none w-100 text-dark' do %>
          <h1 class=""> <%= topic.title%> </h1>
          </p>
            <div>
              <%= link_to topic_path(topic), class:'text-decoration-none w-100 text-dark' do %>
                <%= topic.replies.count%> Comment(s)
                <i class="fa-solid fa-comments"></i>
            <%end%>
            </div>
        <%end%>
      </div>
    <%end%>
  </div>
</div>
</div>
</div>

app/views/topics/new.html.erb
<%= render 'shared/navbar' %>
<%= render "form", topic: @topic %>

app/views/topics/show.html.erb
<%= render 'shared/navbar' %>
<%= render 'shared/converter' %>
<div class="cards">
  <div class="forum bg-dark">
    <div class=" header d-flex align-items-center justify-content-between">
      <h2 class="text-dark">RoundEarthForum</h2>
      <% if current_user && (@topic.user == current_user || current_user.admin) %>
        <a class=" bt text-light btn btn-light bg-dark" data-bs-toggle="collapse" href="#collapseExample2" role="button" aria-expanded="false" aria-controls="collapseExample2">Edit Topic</a>
      <%end%>
    </div>
    <div class="back-topics py-3" style="background-image: linear-gradient(rgba(0,0,0,0.4),rgba(0,0,0,0.4)), url(https://images.pexels.com/photos/586056/pexels-photo-586056.jpeg);">
      <div class="container">
        <div class="collapse mx-5" id="collapseExample2">
          <%= render "form", topic: @topic %>
        </div>
        <div class="topic-topic-1 m-5 p-4 text-center rounded-style">
          <h1 class="text-dark"> <%=@topic.title%> </h1>
          <h5 class="text-dark"> <%=@topic.description%></h5>
          <br/>
          <% if current_user && (@topic.user == current_user || current_user.admin) %>
            <%= link_to topic_path(@topic), class:"text-dark", data: {turbo_method: :delete, turbo_confirm: "Are you sure?"} do %>
              Delete <i class="fa-regular fa-trash-can"></i>
            <%end%>
          <%end%>
        </div>
        <div class="header-2 d-flex align-items-center justify-content-between">
          <h1 class="text-light ">Comments:</h1>
          <% if current_user %>
            <a class="btn btn btn-light" data-bs-toggle="collapse" href="#collapseExample" role="button" aria-expanded="false" aria-controls="collapseExample">New Comment</a>
          <%end%>
        </div>
        <div class="px-5 text-center">
          <div class="collapse" id="collapseExample">
            <%= render"form_reply", topic: @topic %>
          </div>
        </div>
        <% @topic.replies.reverse.each do |reply| %>
          <div class="rounded-style topic-topic-1 m-5 p-4 text-dark">
            Published <%=time_ago_in_words(reply.created_at)%> ago, sent by:
            <strong><% if reply.user.photo.attached? %>
                <%= cl_image_tag reply.user.photo.key,:width=>25, :height=>25, :gravity=>"face", :crop=>"fill", class:"avatar dropdown-toggle", id:"navbarDropdown", "type" => "button", "data-bs-toggle" => "dropdown", "aria-haspopup" => "true", "aria-expanded" => "false" %>
              <% else %>
                <%= image_tag "planetinha.png",:width=>20, :height=>20, :gravity=>"face", :crop=>"fill", class:"avatar dropdown-toggle", id:"navbarDropdown", "type" => "button", "data-bs-toggle" => "dropdown", "aria-haspopup" => "true", "aria-expanded" => "false" %>
              <% end %><%= reply.user.nickname%></p>
          </strong>
          <h3><%= reply.content %></h3>
          <% if current_user && (reply.user == current_user || current_user.admin) %>
            <br/>
            <%= link_to reply_path(reply), class:"text-dark", data: {turbo_method: :delete, turbo_confirm: "Are you sure?"} do %>
              Delete <i class="fa-regular fa-trash-can"></i>
            <% end %>
          <%end%>
          <br/>
          <% reply.comments.reverse.each do |comment| %>
            <hr>
            Answered <%=time_ago_in_words(comment.created_at)%> ago, sent by:
            <strong> <% if comment.user.photo.attached? %>
                <%= cl_image_tag comment.user.photo.key,:width=>25, :height=>25, :gravity=>"face", :crop=>"fill", class:"avatar dropdown-toggle", id:"navbarDropdown", "type" => "button", "data-bs-toggle" => "dropdown", "aria-haspopup" => "true", "aria-expanded" => "false" %>
              <% else %>
                <%= image_tag "planetinha.png",:width=>20, :height=>20, :gravity=>"face", :crop=>"fill", class:"avatar dropdown-toggle", id:"navbarDropdown", "type" => "button", "data-bs-toggle" => "dropdown", "aria-haspopup" => "true", "aria-expanded" => "false" %>
              <% end %><%= comment.user.nickname%></p>
          </strong>
          <h5><%= comment.content %></h5>
          <% if current_user && (comment.user == current_user || current_user.admin) %>
            <br/>
            <%= link_to comment_path(comment), class:"text-dark", data: {turbo_method: :delete, turbo_confirm: "Are you sure?"} do %>
              Delete <i class="fa-regular fa-trash-can"></i>
            <%end%>
          <% end %>
        <% end %>
        <hr>
        <% if current_user %>
          <%= simple_form_for [ @topic, reply, @comment] do |f| %>
            <div class="container">
              <div class="rounded-style form-comment-1 p-4 text-center">
                <%= f.error_notification %>
                <%= f.error_notification message: f.object.errors[:base].to_sentence if f.object.errors[:base].present? %>
                <div class="form-inputs">
                  <%= f.input :content, label:"Answer" %>
                </div>
                <div class="form-actions">
                  <%= f.button :submit, 'Submit', class: 'btn btn-dark rounded-pill d-block w-100' %>
                </div>
              </div>
            </div>
          <% end %>
        <%end%>
      </div>
    <%end%>
  </div>
</div>
</div>