config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  root to: "pages#home"
  get "about", to: "pages#about"
  get "features", to: "pages#features"
  get "dashboard", to: "pages#dashboard"
  get 'content', to: "pages#content"
  get "calculator", to: "pages#calculator"
  get "distance", to: 'pages#distance'
  get "converted", to: 'pages#converted'
  get "chatrooms", to: 'pages#chatrooms'
  resources :articles do
    resources :likes
  end
  resources :topics do
    resources :replies, only: [:new, :create] do
      resources :comments, only: [:create]
    end
  end
  resources :replies, only: [:destroy]
  resources :comments, only: [:destroy]
  resources :chatrooms, only: :show do
    resources :messages, only: :create
  end
  resources :requests, only: [:create, :update, :destroy]

  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html
  # Defines the root path route ("/")
  # root "articles#index"
end

app/views/shared/_about.html.erb
<div class="back-articles" style="background-image: linear-gradient(rgba(0,0,0,0.4),rgba(0,0,0,0.4)), url(https://images.pexels.com/photos/586056/pexels-photo-586056.jpeg);">
  <div class="container justify-content-center">
    <h1 class="about-title pb-3 mb-3 ">A 4.54 billion years old tradition</h1>
    <br>
  </div>
  <div class="container about justify-content-center">
    <p>Since then, <em> Round Earth Society</em> has been challenging assumptions and pursuing truth.</p>
    <p>When the founders of <em>Round Earth Society</em> gathered in São Paulo in the spring of 2022, during Le Wagon Bootcamp, they wanted to create a website that would be indispensable for the kind of reader who was deeply engaged with the most consequential issues of the Earth. The men and women who created this website had an overarching, prophetic vision—they were fierce opponents of flat earth society—but they were also moved to overcome what they saw as the limits of denialism, believing that the free exchange of ideas across ideological lines was crucial to the great Humanity experiment. Their goal was to publish the most urgent essays, the most vital literature; they wanted to pursue truth and disrupt nonsense without regard for the number of likes.</p>
    <p>We understand these themes as timeless. The core principles of the founders are core principles for most: reason should always guide opinion; ideas have consequences, sometimes world-historical consequences; the knowledge we have about the world is partial and provisional, and subject to analysis, scrutiny, and revision.</p>
    <p>We will deal frankly with everyone, not rank ourselves with any sect of anties, but with that body of men which is in favor of the truth.</p>
  </div>
  <div class="container about justify-content-center">
    <h2>Our publishers:</h2>
    <div class="cards-article-grid">
      <% @publishers.each do |publisher|%>
        <div class="card-article">
          <% if publisher.photo.attached? %>
            <%= cl_image_tag publisher.photo.key, :width => 1920, :height => 1080, crop: :limit %>
          <% else %>
            <%= image_tag 'astronauta.jpg', style:"width = 1920; height = 1080;" %>
          <% end %>
          <div class="card-article-infos">
            <h4><%= publisher.first_name %></h4>
            <h4><%= publisher.last_name %></h4>
            <p><%= publisher.description %></p>
          </div>
        </div>
      <%end%>
    </div>
  </div>
  <div class="container about justify-content-center">
    <h2>Our staff:</h2>
    <div class="cards-article-grid">
      <% @admins.each do |admin|%>
        <div class="card-article">
          <% if admin.photo.attached? %>
            <%= cl_image_tag admin.photo.key, :width => 1920, :height => 1080, crop: :limit %>
          <% else %>
            <%= image_tag 'astronauta.jpg', style:"width = 1920; height = 1080;" %>
          <% end %>
          <div class="card-article-infos">
            <h4><%= admin.first_name %></h4>
            <h4><%= admin.last_name %></h4>
            <p><%= admin.description %></p>
          </div>
        </div>
      <%end%>
    </div>
  </div>
</div>

app/views/shared/_banner.html.erb
<div class="banner" style="background-image: linear-gradient(rgba(0,0,0,0.4),rgba(0,0,0,0.4)), url(https://images.unsplash.com/photo-1446776811953-b23d57bd21aa?ixlib=rb-4.0.3&ixid=MnwxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8&auto=format&fit=crop&w=1472&q=80);">
  <div class="container">
    <div>
      <h1 class="" >Round Earth Society</h1>
        <p data-controller="banner" class="animejs">Challenging assumptions and pursuing truth</p>
    </div>
    <div class="btn-group" role="group" aria-label="Basic example">
    <%= link_to "Believer", articles_path(believer: true), class: "btn  btn-bk" %>
    <%= link_to "Non-believer", articles_path(believer: false),  class: "btn  btn-bk" %>
    </div>
  </div>
</div>

app/views/shared/_believer.html.erb
<div class="back-articles" style="background-image: linear-gradient(rgba(0,0,0,0.4),rgba(0,0,0,0.4)), url(https://images.unsplash.com/photo-1446776811953-b23d57bd21aa?ixlib=rb-4.0.3&ixid=MnwxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8&auto=format&fit=crop&w=1472&q=80);">
  <div class="container text-center">
    <div>
      <h1 class="pb-3 mb-3">Welcome believer!</h1>
      <br>
      <br>
    </div>
    <div class="cards-article">
      <% @articles.each do |article|%>
        <div class="card-trip">
          <%= cl_image_tag article.photo.key, :width => 1920, :height => 1080, crop: :limit if article.photo.attached? %>
          <div class="card-trip-infos">
            <div>
            <h4><%= article.title %></h4>
              <p><%= article.subtitle %></p>
            </div>
              <a href="/articles/<%=article.id%>" class="btn-flat card-trip-user">READ MORE...</a>
          </div>
        </div>
      <%end%>
    </div>
  </div>
</div>

app/views/shared/_chatrooms.html.erb
<div class="forum bg-dark">
  <div class=" header d-flex align-items-center justify-content-between">
     <h2 class=" text-dark">RoundEarthChatroom</h2>
      <a class=" bt text-light btn btn-light bg-dark" data-bs-toggle="collapse" href="#collapseExample" role="button" aria-expanded="false" aria-controls="collapseExample">New Chat</a>
  </div>

app/views/shared/_converted_counter.html.erb
<div data-controller="converter">

  <button class="custom-btn btn-16 my-1 " data-converter-target="button">
      Converted flat-earthers: <span data-converter-target="number"> <%= User.where(converted: true).count %> </span>
  </button>

</div>

app/views/shared/_converter.html.erb
<% if current_user && !current_user.believer %>
  <div class="alert-converted">
    <%= link_to 'I give up, earth is ROUND', converted_path, class:'btn btn-primary rounded-pill' %>
  </div>
<% end %>

app/views/shared/_features.html.erb
<div class="back-articles" style="background-image: linear-gradient(rgba(0,0,0,0.4),rgba(0,0,0,0.4)), url(https://images.unsplash.com/photo-1457364887197-9150188c107b?ixlib=rb-4.0.3&ixid=MnwxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8&auto=format&fit=crop&w=870&q=80);">
  <div class="container text-center banner">
    <h1 class="pb-3 mb-3">Play with our features!</h1>
    <%= link_to 'Distance Calculator 🌎', calculator_path, class:"btn btn-bk" %>
  </div>
</div>

app/views/shared/_flashes.html.erb
<% if notice %>
  <div class="alert alert-info alert-dismissible fade show m-1" role="alert">
    <%= notice %>
    <button type="button" class="btn-close" data-bs-dismiss="alert" aria-label="Close">
    </button>
  </div>
<% end %>
<% if alert %>
  <div class="alert alert-warning alert-dismissible fade show m-1" role="alert">
    <%= alert %>
    <button type="button" class="btn-close" data-bs-dismiss="alert" aria-label="Close">
    </button>
  </div>
<% end %>

app/views/shared/_list.html.erb
<div class="back-articles bg-dark" >
  <div class="container bg-dark">
    <div>
      <% if @believer %>
        <h1 class="article-text-style">Welcome Believer</h1>
        <h4 class="article-subtitle-style">The Earth is very pleased to have you as a member of our community. Make yourself at home... Here, you'll be able to access the latest news, discuss with friends and, of course, share our articles with people you know.</h4>
      <% elsif @believer.nil? %>
        <h1 class="article-text-style">Articles List</h1>
        <h4 class="article-subtitle-style">It's great to have you with us, make yourself at home... Here, you'll be able to access the latest news and share our articles with people you know.</h4>
      <% else %>
        <h1 class="article-text-style">Welcome Non-believer</h1>
        <h4 class="article-subtitle-style">Well... it's great to have you with us! We hope to spin and crack your old square beliefs! Here, you'll be able to access the latest news, discuss with friends and, of course, share our articles with people you know.</h4>
      <% end %>
      <br>
      <br>
    </div>
    <%= turbo_frame_tag 'search' do %>
      <div class="row mx-auto my-auto justify-content-center arrow-wrapper">
        <div id="recipeCarousel" class="carousel slide" data-bs-ride="carousel">
          <div class="carousel-inner" data-controller="carousel" role="listbox">
            <% articles.each_with_index do |article, index|%>
              <div class="carousel-item <%="active"if index.zero? %>" data-carousel-target="cards">
                <div class="col-md-3">
                  <div class="card-article p-2">
                    <% if article.photo.attached? %>
                      <%= cl_image_tag article.photo.key, :width => 1920, :height => 1080, crop: :limit %>
                    <% else %>
                      <%= image_tag 'astronauta.jpg', style:"width = 1920; height = 1080;" %>
                    <% end %>
                    <div class="card-article-infos">
                      <div>
                        <h4><%= article.title %></h4>
                        <p><%= article.subtitle %></p>
                      </div>
                      <a href="/articles/<%=article.id%>" class="btn-flat card-article-user">Read More...</a>
                    </div>
                  </div>
                </div>
              </div>
            <%end%>
          </div>
        </div>
        <a class="carousel-control-prev bg-transparent w-aut" href="#recipeCarousel" role="button" data-bs-slide="prev">
          <span class="carousel-control-prev-icon" aria-hidden="true"></span>
        </a>
        <a class="carousel-control-next bg-transparent w-aut" href="#recipeCarousel" role="button" data-bs-slide="next">
          <span class="carousel-control-next-icon" aria-hidden="true"></span>
        </a>
      </div>
    <% end %>
  </div>
</div>

app/views/shared/_navbar.html.erb
<nav class="navbar navbar-expand-lg navbar-dark bg-dark">
  <div class="container-fluid">
    <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
      <span class="navbar-toggler-icon"></span>
    </button>
    <div class="collapse navbar-collapse" id="navbarSupportedContent">
      <ul class="navbar-nav me-auto mb-2 mb-lg-0">
      <% if current_user == nil %>
        <li class="nav-item">
          <a class="nav-link" href="/">HOME</a>
        </li>
        <%end%>
        <li class="nav-item">
          <a class="nav-link" href="/articles">ARTICLES</a>
        </li>
        <li class="nav-item">
          <a class="nav-link" href="/topics">FORUM</a>
        </li>
          <li class="nav-item">
            <a class="nav-link" aria-current="page" href="/features">FEATURES</a>
          </li>
        <li class="nav-item">
          <a class="nav-link" href="/about">ABOUT</a>
        </li>
          <%= form_with url: articles_path,
                        method: :get,
                        class: "d-flex",
                        data: {turbo_frame: 'search', controller: 'search'} do |f| %>
            <%= f.text_field :query,
                            value: params[:query],
                            class: "form-control",
                            type: "search",
                            placeholder: "🔎 Search Articles...",
                            label: "Search",
                            data: {action: 'keyup->search#perform'} %>
          <% end %>
      </ul>
      <ul class="navbar-nav">
        <li class="nav-item mx-5"><%= render 'shared/converted_counter' %></li>
        <% if user_signed_in? %>
          <li class="nav-item">
            <%= link_to current_user.nickname, "/dashboard", class: "nav-link active my-1", target:'_blank' %>
          </li>
          <li class="nav-item dropdown">
            <%= render 'shared/user_avatar' %>
            <div class="dropdown-menu dropdown-menu-end" aria-labelledby="navbarDropdown">
              <%= link_to "Edit Profile", "/users/edit", class: "dropdown-item" %>
              <%= link_to "Dashboard", dashboard_path, class: "dropdown-item", target:'_blank' %>
              <%= link_to "Chatrooms", chatroom_path(1), class: "dropdown-item", target: "_blank" %>
              <%= link_to "Log out", destroy_user_session_path, data: {turbo_method: :delete}, class: "dropdown-item" %>
            </div>
          </li>
        <% else %>
        
          <li class="nav-item">
            <%= link_to "SIGN UP", new_user_registration_path, class: "nav-link" %>
          </li>
          <li class="nav-item">
            <%= link_to "LOGIN", new_user_session_path, class: "nav-link" %>
          </li>
         <% end %>
      </ul>
    </div>
  </div>
</nav>

app/views/shared/_user_avatar.html.erb
<% if current_user.photo.attached? %>
  <%= cl_image_tag current_user.photo.key,:width=>50, :height=>50, :gravity=>"face", :crop=>"fill", class:"avatar dropdown-toggle", id:"navbarDropdown", "type" => "button", "data-bs-toggle" => "dropdown", "aria-haspopup" => "true", "aria-expanded" => "false" %>
<% else %>
  <%= image_tag "planetinha.png",:width=>40, :height=>40, :gravity=>"face", :crop=>"fill", class:"avatar dropdown-toggle", id:"navbarDropdown", "type" => "button", "data-bs-toggle" => "dropdown", "aria-haspopup" => "true", "aria-expanded" => "false" %>
<% end %>